export interface GalleryAsset {
  fileName: string;
  alt: string;
}

export const GALLERY_ASSETS: GalleryAsset[] = [
  { fileName: 'IMG (10).jpg', alt: 'Fotografie din galeria centrului #1' },
  { fileName: 'IMG (104).jpg', alt: 'Fotografie din galeria centrului #2' },
  { fileName: 'IMG (109).JPG', alt: 'Fotografie din galeria centrului #3' },
  { fileName: 'IMG (110).JPG', alt: 'Fotografie din galeria centrului #4' },
  { fileName: 'IMG (113).JPG', alt: 'Fotografie din galeria centrului #5' },
  { fileName: 'IMG (115).JPG', alt: 'Fotografie din galeria centrului #6' },
  { fileName: 'IMG (116).JPG', alt: 'Fotografie din galeria centrului #7' },
  { fileName: 'IMG (118).jpg', alt: 'Fotografie din galeria centrului #8' },
  { fileName: 'IMG (12).jpg', alt: 'Fotografie din galeria centrului #9' },
  { fileName: 'IMG (120).jpg', alt: 'Fotografie din galeria centrului #10' },
  { fileName: 'IMG (123).jpg', alt: 'Fotografie din galeria centrului #11' },
  { fileName: 'IMG (128).jpg', alt: 'Fotografie din galeria centrului #12' },
  { fileName: 'IMG (14).jpg', alt: 'Fotografie din galeria centrului #13' },
  { fileName: 'IMG (140).jpg', alt: 'Fotografie din galeria centrului #14' },
  { fileName: 'IMG (142).jpg', alt: 'Fotografie din galeria centrului #15' },
  { fileName: 'IMG (143).jpg', alt: 'Fotografie din galeria centrului #16' },
  { fileName: 'IMG (145).jpg', alt: 'Fotografie din galeria centrului #17' },
  { fileName: 'IMG (149).jpg', alt: 'Fotografie din galeria centrului #18' },
  { fileName: 'IMG (152).jpg', alt: 'Fotografie din galeria centrului #19' },
  { fileName: 'IMG (156).jpg', alt: 'Fotografie din galeria centrului #20' },
  { fileName: 'IMG (161).jpg', alt: 'Fotografie din galeria centrului #21' },
  { fileName: 'IMG (168).jpg', alt: 'Fotografie din galeria centrului #22' },
  { fileName: 'IMG (169).jpg', alt: 'Fotografie din galeria centrului #23' },
  { fileName: 'IMG (171).jpg', alt: 'Fotografie din galeria centrului #24' },
  { fileName: 'IMG (173).jpg', alt: 'Fotografie din galeria centrului #25' },
  { fileName: 'IMG (175).jpg', alt: 'Fotografie din galeria centrului #26' },
  { fileName: 'IMG (22).JPG', alt: 'Fotografie din galeria centrului #27' },
  { fileName: 'IMG (30).jpg', alt: 'Fotografie din galeria centrului #28' },
  { fileName: 'IMG (36).jpg', alt: 'Fotografie din galeria centrului #29' },
  { fileName: 'IMG (40).jpg', alt: 'Fotografie din galeria centrului #30' },
  { fileName: 'IMG (43).jpg', alt: 'Fotografie din galeria centrului #31' },
  { fileName: 'IMG (46).jpg', alt: 'Fotografie din galeria centrului #32' },
  { fileName: 'IMG (51).jpg', alt: 'Fotografie din galeria centrului #33' },
  { fileName: 'IMG (56).jpg', alt: 'Fotografie din galeria centrului #34' },
  { fileName: 'IMG (59).jpg', alt: 'Fotografie din galeria centrului #35' },
  { fileName: 'IMG (63).jpg', alt: 'Fotografie din galeria centrului #36' },
  { fileName: 'IMG (65).JPG', alt: 'Fotografie din galeria centrului #37' },
  { fileName: 'IMG (68).JPG', alt: 'Fotografie din galeria centrului #38' },
  { fileName: 'IMG (73).JPG', alt: 'Fotografie din galeria centrului #39' },
  { fileName: 'IMG (77).jpg', alt: 'Fotografie din galeria centrului #40' },
  { fileName: 'IMG (87).jpg', alt: 'Fotografie din galeria centrului #41' },
  { fileName: 'IMG (89).jpg', alt: 'Fotografie din galeria centrului #42' },
  { fileName: 'IMG (96).JPG', alt: 'Fotografie din galeria centrului #43' },
  { fileName: 'IMG (99).JPG', alt: 'Fotografie din galeria centrului #44' },
];
